Advanced Aggregation Functions: Aggregate() Function

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'groups': ['X', 'Y', 'Z', 'X', 'Y', 'Z'],
                   'val1': [2, 15, 25, 14, 3, 91],
                   'val2': [92,245,325,254,103,961]})

In [3]:
df

  groups  val1  val2
0      X     2    92
1      Y    15   245
2      Z    25   325
3      X    14   254
4      Y     3   103
5      Z    91   961

In [4]:
df.groupby("groups").mean()

        val1   val2
groups
X        8.0  173.0
Y        9.0  174.0
Z       58.0  643.0

In [5]:
df.groupby("groups").aggregate(["mean", np.median, min, "sum"])

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_2264\3885689337.py:1: FutureWarning: The provided callable <function median at 0x0000010D8B682B60> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby("groups").aggregate(["mean", np.median, min, "sum"])
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_2264\3885689337.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby("groups").aggregate(["mean", np.median, min, "sum"])

        val1                   val2
        mean median min  sum   mean median  min   sum
groups
X        8.0    8.0   2   16  173.0  173.0   92   346
Y        9.0    9.0   3   18  174.0  174.0  103   348
Z       58.0   58.0  25  116  643.0  643.0  325  1286

In [6]:
df.groupby("groups").aggregate({"val1" : "mean", "val2" : "median"})

        val1   val2
groups
X        8.0  173.0
Y        9.0  174.0
Z       58.0  643.0

Advanced Aggregation Functions: Filter() Function

In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.DataFrame({'groups': ['X', 'Y', 'Z', 'X', 'Y', 'Z'],
                   'val1': [2, 15, 25, 14, 3, 91],
                   'val2': [92,245,325,254,103,961]})

In [9]:
df

  groups  val1  val2
0      X     2    92
1      Y    15   245
2      Z    25   325
3      X    14   254
4      Y     3   103
5      Z    91   961

In [10]:
df.groupby("groups").mean()

        val1   val2
groups
X        8.0  173.0
Y        9.0  174.0
Z       58.0  643.0

In [11]:
def example_function(x):
    return x["val2"].mean() < 200

In [12]:
df.groupby("groups").filter(example_function)

  groups  val1  val2
0      X     2    92
1      Y    15   245
3      X    14   254
4      Y     3   103

In [13]:
df.groupby("groups").std()

             val1        val2
groups
X        8.485281  114.551299
Y        8.485281  100.409163
Z       46.669048  449.719913

In [14]:
df.groupby("groups").filter(lambda x : x["val2"].std() > 105)

  groups  val1  val2
0      X     2    92
2      Z    25   325
3      X    14   254
5      Z    91   961

Advanced Aggregation Functions: Transform() Function

In [15]:
import pandas as pd
import numpy as np

In [16]:

df = pd.DataFrame({'groups': ['X', 'Y', 'Z', 'X', 'Y', 'Z'],
                   'val1': [2, 15, 25, 14, 3, 91],
                   'val2': [92,245,325,254,103,961]})

In [17]:
df

  groups  val1  val2
0      X     2    92
1      Y    15   245
2      Z    25   325
3      X    14   254
4      Y     3   103
5      Z    91   961

In [18]:
df_new = df.loc[:, "val1":"val2"]

In [19]:
df_new

   val1  val2
0     2    92
1    15   245
2    25   325
3    14   254
4     3   103
5    91   961

In [20]:
def normalize(x):
    return (x - x.min()) / (x.max() - x.min())

In [21]:
df_new.transform(normalize)

       val1      val2
0  0.000000  0.000000
1  0.146067  0.176064
2  0.258427  0.268124
3  0.134831  0.186421
4  0.011236  0.012658
5  1.000000  1.000000

In [22]:
df_new.loc[1, "val1"]

np.int64(15)

In [23]:
(df_new.loc[1, "val1"] - df["val1"].min()) / (df["val1"].max() - df["val1"].min())

np.float64(0.14606741573033707)

In [24]:
df_new

   val1  val2
0     2    92
1    15   245
2    25   325
3    14   254
4     3   103
5    91   961

In [25]:
df_new.transform(lambda a : np.sin(a))

       val1      val2
0  0.909297 -0.779466
1  0.650288 -0.044213
2 -0.132352 -0.988036
3  0.990607  0.451999
4  0.141120  0.622989
5  0.105988 -0.321537

In [26]:
np.sin(df_new.val2)

0   -0.779466
1   -0.044213
2   -0.988036
3    0.451999
4    0.622989
5   -0.321537
Name: val2, dtype: float64

Advanced Aggregation Functions: Apply() Function

In [27]:
import pandas as pd
import numpy as np

In [28]:
df = pd.DataFrame({'groups': ['X', 'Y', 'Z', 'X', 'Y', 'Z'],
                   'val1': [2, 15, 25, 14, 3, 91],
                   'val2': [92,245,325,254,103,961]})

In [29]:
df

  groups  val1  val2
0      X     2    92
1      Y    15   245
2      Z    25   325
3      X    14   254
4      Y     3   103
5      Z    91   961

In [30]:
df.apply(np.sum)

groups    XYZXYZ
val1         150
val2        1980
dtype: object

In [31]:
df.apply(np.mean)

TypeError: Could not convert string 'XYZXYZ' to numeric

In [32]:
df_new = df.loc[:, "val1":"val2"]

In [33]:
df_new

   val1  val2
0     2    92
1    15   245
2    25   325
3    14   254
4     3   103
5    91   961

In [34]:
df_new.apply(np.mean)

val1     25.0
val2    330.0
dtype: float64

In [35]:
df_new["val2"].mean()

np.float64(330.0)

In [36]:
df_new.apply(np.mean, axis = 1)

0     47.0
1    130.0
2    175.0
3    134.0
4     53.0
5    526.0
dtype: float64

In [37]:
df.groupby("groups").apply(np.mean)

groups
X     90.5
Y     91.5
Z    350.5
dtype: float64

In [38]:
df2 = pd.DataFrame({'val1':[2, 4, 6, 8, 10], 'val2':['Turkey', 'UK', 'Australia','Philippines', 'Egypt']})

In [39]:
df2

   val1         val2
0     2       Turkey
1     4           UK
2     6    Australia
3     8  Philippines
4    10        Egypt

In [41]:
def cube(x):
    return x ** 3

In [42]:
df2.val1.apply(cube)

0       8
1      64
2     216
3     512
4    1000
Name: val1, dtype: int64

In [43]:
df2.val2.apply(len)

0     6
1     2
2     9
3    11
4     5
Name: val2, dtype: int64

Examining the Data Set 3

In [44]:
import pandas as pd
import seaborn as sns
import numpy as np

In [45]:
df = sns.load_dataset("titanic")

In [46]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

Pivot Tables in Pandas Library

In [48]:
import pandas as pd
import seaborn as sns
import numpy as np

In [49]:
df = sns.load_dataset("titanic")

In [50]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [51]:
df.groupby("sex")[["survived"]].mean()

        survived
sex
female  0.742038
male    0.188908

In [52]:
df.groupby(["sex", "embark_town"])[["survived"]].mean()

                    survived
sex    embark_town
female Cherbourg    0.876712
       Queenstown   0.750000
       Southampton  0.689655
male   Cherbourg    0.305263
       Queenstown   0.073171
       Southampton  0.174603

In [53]:
df.groupby(["sex", "embark_town"])[["survived"]].mean().unstack()

             survived
embark_town Cherbourg Queenstown Southampton
sex
female       0.876712   0.750000    0.689655
male         0.305263   0.073171    0.174603

In [54]:
df.pivot_table("survived", index = "sex", columns = "embark_town")

embark_town  Cherbourg  Queenstown  Southampton
sex
female        0.876712    0.750000     0.689655
male          0.305263    0.073171     0.174603

In [55]:
df.pivot_table("survived", index = "sex", columns = "embark_town", aggfunc = ["sum", "mean", "std"])

                  sum                             mean                         \
embark_town Cherbourg Queenstown Southampton Cherbourg Queenstown Southampton
sex
female             64         27         140  0.876712   0.750000    0.689655
male               29          3          77  0.305263   0.073171    0.174603

                  std
embark_town Cherbourg Queenstown Southampton
sex
female       0.331042   0.439155    0.463778
male         0.462962   0.263652    0.380058

In [56]:
df.pivot_table("survived", index = ["sex", "class"], columns = "embark_town", aggfunc = ["sum", "mean", "std"])

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_2264\1491890403.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table("survived", index = ["sex", "class"], columns = "embark_town", aggfunc = ["sum", "mean", "std"])
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_2264\1491890403.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table("survived", index = ["sex", "class"], columns = "embark_town", aggfunc = ["sum", "mean", "std"])
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_2264\1491890403.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table("survived", index = ["sex", "class"], columns = "embark_town", aggfunc = ["sum", "mean", "std"])

                    sum                             mean             \
embark_town   Cherbourg Queenstown Southampton Cherbourg Queenstown
sex    class
female First         42          1          46  0.976744   1.000000
       Second         7          2          61  1.000000   1.000000
       Third         15         24          33  0.652174   0.727273
male   First         17          0          28  0.404762   0.000000
       Second         2          0          15  0.200000   0.000000
       Third         10          3          34  0.232558   0.076923

                                std
embark_town   Southampton Cherbourg Queenstown Southampton
sex    class
female First     0.958333  0.152499        NaN    0.201941
       Second    0.910448  0.000000   0.000000    0.287694
       Third     0.375000  0.486985   0.452267    0.486897
male   First     0.354430  0.496796        NaN    0.481397
       Second    0.154639  0.421637        NaN    0.363439
       Third     0.128302  0.427463   0.269953    0.335058

External Data Entry to Pandas Library

Outputting as an Excel File

In [2]:
import pandas as pd
import openpyxl

In [3]:
df1 = pd.DataFrame({'employee': ['Julia', 'Marie', 'Adam', 'Nicole'],
                     'department': ['Data Science', 'Web Development', 'Data Science', 'Cyber Security'],
                     'Year': ['2005', '2008', '2011', '2002']})
   
df2 = pd.DataFrame({'employee': ['Nicole', 'Adam', 'Julia', 'Marie'],
                          'country': ['Canada', 'England', 'USA', 'Germany'],
                          'salary': ['22000', '16000', '20000', '17500']})

In [4]:
df3 = pd.merge(df1, df2)

In [5]:
df3.to_excel("excel_sample.xlsx", sheet_name = "new_sheet1", index = False)

In [6]:
df4 = pd.read_excel("excel_sample.xlsx")

In [7]:
df4

  employee       department  Year  country  salary
0    Julia     Data Science  2005      USA   20000
1    Marie  Web Development  2008  Germany   17500
2     Adam     Data Science  2011  England   16000
3   Nicole   Cyber Security  2002   Canada   22000