Creating a Pandas Series with a List

In [409]:
import pandas as pd

In [410]:
pd.Series([10, 20, 30, 40, 50])

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [411]:
list_data = [2,4,6,8,10]

In [412]:
list_index = ["a", "b", "c", "d", "e"]

In [413]:
variable = pd.Series(data = list_data, index = list_index, dtype= "float")

In [414]:
variable

a     2.0
b     4.0
c     6.0
d     8.0
e    10.0
dtype: float64

In [415]:
type(variable)

pandas.core.series.Series

In [416]:
list_data = [2,4,6,8,10,12]

In [417]:
list_index = ["a", "b", "c", "d", "e"]

In [418]:
#variable = pd.Series(data = list_data, index = list_index, dtype = "float")

Creating a Pandas Series with a Dictionary

In [419]:
import pandas as pd

In [420]:
dictionary = {"ferrari" : 334.7, "porche" : 337.9, "lamborghini" : 349}

In [421]:
pd.Series(data = dictionary)

ferrari        334.7
porche         337.9
lamborghini    349.0
dtype: float64

In [422]:
variable = pd.Series(data = dictionary, index = ["porche", "bugatti", "ferrari"])

In [423]:
variable

porche     337.9
bugatti      NaN
ferrari    334.7
dtype: float64

Creating Pandas Series with Numpy Array

In [424]:
import numpy as np
import pandas as pd

In [425]:
example = np.array([1, 3.3, 5, 7.2, 9])
labels = np.array(["a", "b", "c", "d", "e"])

In [426]:
variable = pd.Series(data = example, index = labels)

In [427]:
variable

a    1.0
b    3.3
c    5.0
d    7.2
e    9.0
dtype: float64

Object Types in Series

In [428]:
import pandas as pd

In [429]:
pd.Series(["world", 100, 5.8, False])

0    world
1      100
2      5.8
3    False
dtype: object

In [430]:
example = pd.Series(["world", 100, 5.8, False])

In [431]:
example[0]

'world'

In [432]:
print(type(example[0]))

<class 'str'>

In [433]:
print(type(example[1]))
print(type(example[2]))
print(type(example[3]))

<class 'int'>
<class 'float'>
<class 'bool'>

In [434]:
pd.Series([sum, type, max])

0    <built-in function sum>
1             <class 'type'>
2    <built-in function max>
dtype: object

Examining the Primary Features of the Pandas Series

In [435]:
import pandas as pd

In [436]:
example = pd.Series([10, 20, 30, 40, 50, 60, 70])

In [437]:
example

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [438]:
example.axes

[RangeIndex(start=0, stop=7, step=1)]

In [439]:
example.dtype

dtype('int64')

In [440]:
example.size

7

In [441]:
example.ndim

1

In [442]:
example.head()

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [443]:
example.tail()

2    30
3    40
4    50
5    60
6    70
dtype: int64

Most Applied Methods on Pandas Series

In [444]:
import pandas as pd

In [445]:
variable = pd.Series([8, 3, 6, 5, 1], index = ["b", "d", "c", "a", "e"])

In [446]:
variable

b    8
d    3
c    6
a    5
e    1
dtype: int64

In [447]:
new_variable = variable.sort_index()

In [448]:
new_variable

a    5
b    8
c    6
d    3
e    1
dtype: int64

In [449]:
new_variable2 = variable.sort_values()

In [450]:
new_variable2

e    1
d    3
a    5
c    6
b    8
dtype: int64

In [451]:
variable

b    8
d    3
c    6
a    5
e    1
dtype: int64

In [452]:
variable.isin([6,1])

b    False
d    False
c     True
a    False
e     True
dtype: bool

In [453]:
variable[variable.isin([6,1])]

c    6
e    1
dtype: int64

In [454]:
variable.values

array([8, 3, 6, 5, 1])

In [455]:
[i for i in variable.values]

[np.int64(8), np.int64(3), np.int64(6), np.int64(5), np.int64(1)]

In [456]:
variable.index

Index(['b', 'd', 'c', 'a', 'e'], dtype='object')

In [457]:
[i for i in variable.index]

['b', 'd', 'c', 'a', 'e']

In [458]:
variable.items

<bound method Series.items of b    8
d    3
c    6
a    5
e    1
dtype: int64>

In [459]:
variable.items()

In [460]:
list(variable.items())

[('b', 8), ('d', 3), ('c', 6), ('a', 5), ('e', 1)]

In [461]:
for index, value in variable.items():
    print(index, "-", value)

b - 8
d - 3
c - 6
a - 5
e - 1

Indexing and Slicing Pandas Series

In [462]:
import pandas as pd

In [463]:
example = pd.Series(["+90", "+49", "+33", "+39", "+46", "+47"], index = ["Turkey", "Germany", "France", "Italy", "Sweden", "Norway"])

In [464]:
example

Turkey     +90
Germany    +49
France     +33
Italy      +39
Sweden     +46
Norway     +47
dtype: object

In [465]:
example["Germany"]

'+49'

In [466]:
example[1]

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_18584\3334167894.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  example[1]

'+49'

In [467]:
example["France" : "Sweden"]

France    +33
Italy     +39
Sweden    +46
dtype: object

In [468]:
example[2:5]

France    +33
Italy     +39
Sweden    +46
dtype: object

In [469]:
example[2:5:2]

France    +33
Sweden    +46
dtype: object

In [470]:
example[["Norway", "Turkey"]]

Norway    +47
Turkey    +90
dtype: object

Creating Pandas DataFrame with List

In [471]:
import pandas as pd

In [472]:
list_example = [5, 10, 15, 20, 25]

In [473]:
list_example

[5, 10, 15, 20, 25]

In [474]:
pd.DataFrame(data = list_example, columns= ["values"], dtype="float")

   values
0     5.0
1    10.0
2    15.0
3    20.0
4    25.0

Creating Pandas DataFrame with NumPy Array

In [475]:
import numpy as np

In [476]:
import pandas as pd

In [477]:
array_example = np.random.randint(0, 50, (4,4))

In [478]:
array_example

array([[33, 29, 24, 36],
       [19, 35, 30, 10],
       [39, 20, 27,  8],
       [22, 26, 23, 46]], dtype=int32)

In [479]:
df = pd.DataFrame(array_example, index = ["a", "b", "c", "d"], columns= ["val1", "val2", "val3", "val4"])

In [480]:
df

   val1  val2  val3  val4
a    33    29    24    36
b    19    35    30    10
c    39    20    27     8
d    22    26    23    46

Creating Pandas DataFrame with Dictionary

In [481]:
import numpy as np

In [482]:
import pandas as pd

In [483]:
x = np.random.randint(10, 50, size = 6)

In [484]:
x

array([47, 32, 19, 12, 28, 38], dtype=int32)

In [485]:
y = np.random.randint(10, 50, size = 6)

In [486]:
z = np.random.randint(10,50, size = 6)

In [487]:
t = np.random.randint(10, 50, size = 6)

In [488]:
dict_example = {"val1" : x, "val2" : y, "val3" : z, "val4" : t}

In [489]:
dict_example

{'val1': array([47, 32, 19, 12, 28, 38], dtype=int32),
 'val2': array([21, 20, 40, 45, 38, 13], dtype=int32),
 'val3': array([29, 30, 24, 15, 15, 16], dtype=int32),
 'val4': array([34, 49, 47, 17, 47, 14], dtype=int32)}

In [490]:
df = pd.DataFrame(dict_example)

In [491]:
df

   val1  val2  val3  val4
0    47    21    29    34
1    32    20    30    49
2    19    40    24    47
3    12    45    15    17
4    28    38    15    47
5    38    13    16    14

Examining the Properties of Pandas DataFrame

In [492]:
import numpy as np
import pandas as pd

In [493]:
x = np.random.randint(10, 50, size = 6)
y = np.random.randint(10, 50, size = 6)
z = np.random.randint(10, 50, size = 6)
t = np.random.randint(10, 50, size = 6)

dict_example = {"val1":x, "val2":y, "val3":z, "val4":t}

df = pd.DataFrame(dict_example)

In [494]:
df

   val1  val2  val3  val4
0    33    23    31    30
1    45    13    27    37
2    25    47    33    21
3    44    39    40    15
4    13    32    46    32
5    28    31    17    35

In [495]:
df.head()

   val1  val2  val3  val4
0    33    23    31    30
1    45    13    27    37
2    25    47    33    21
3    44    39    40    15
4    13    32    46    32

In [496]:
df.tail()

   val1  val2  val3  val4
1    45    13    27    37
2    25    47    33    21
3    44    39    40    15
4    13    32    46    32
5    28    31    17    35

In [497]:
df.head(3)

   val1  val2  val3  val4
0    33    23    31    30
1    45    13    27    37
2    25    47    33    21

In [498]:
df.tail(3)

   val1  val2  val3  val4
3    44    39    40    15
4    13    32    46    32
5    28    31    17    35

In [499]:
df.columns

Index(['val1', 'val2', 'val3', 'val4'], dtype='object')

In [500]:
[i for i in df.columns]

['val1', 'val2', 'val3', 'val4']

In [501]:
df

   val1  val2  val3  val4
0    33    23    31    30
1    45    13    27    37
2    25    47    33    21
3    44    39    40    15
4    13    32    46    32
5    28    31    17    35

In [502]:
df.columns = ["new1", "new2", "new3", "new4"]

In [503]:
df

   new1  new2  new3  new4
0    33    23    31    30
1    45    13    27    37
2    25    47    33    21
3    44    39    40    15
4    13    32    46    32
5    28    31    17    35

In [504]:
df.values

array([[33, 23, 31, 30],
       [45, 13, 27, 37],
       [25, 47, 33, 21],
       [44, 39, 40, 15],
       [13, 32, 46, 32],
       [28, 31, 17, 35]], dtype=int32)

In [505]:
type(df.values)

numpy.ndarray

In [506]:
type(df)

pandas.core.frame.DataFrame

In [507]:
df.shape

(6, 4)

In [508]:
df.size

24

Element Selection Operations in Pandas DataFrames: Lesson 1

In [509]:
import pandas as pd
import numpy as np

In [516]:
np.random.seed(101)
df = pd.DataFrame(data = np.random.randn(6,5), index = "A B C D E F".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [511]:
np.random.seed(101)
df = pd.DataFrame(data = np.random.randn(6,5), index = "A B C D E F".split(), columns = ["v1 v2 v3 v4 v5".split()])

In [512]:
df

         v1        v2        v3        v4        v5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [513]:
df.v1

         v1
A  2.706850
B -0.319318
C  0.528813
D  0.955057
E  0.302665
F  0.390528

In [514]:
df

         v1        v2        v3        v4        v5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [518]:
df["VAL1"]

A    2.706850
B   -0.319318
C    0.528813
D    0.955057
E    0.302665
F    0.390528
Name: VAL1, dtype: float64

In [519]:
df.VAL1

A    2.706850
B   -0.319318
C    0.528813
D    0.955057
E    0.302665
F    0.390528
Name: VAL1, dtype: float64

In [520]:
df[["VAL1"]].values

array([[ 2.70684984],
       [-0.31931804],
       [ 0.52881349],
       [ 0.95505651],
       [ 0.30266545],
       [ 0.39052784]])

In [521]:
df[["VAL1"]]

       VAL1
A  2.706850
B -0.319318
C  0.528813
D  0.955057
E  0.302665
F  0.390528

In [522]:
df[["VAL1"]]["B" : "D"]

       VAL1
B -0.319318
C  0.528813
D  0.955057

In [523]:
df[["VAL1"]] [1:4]

       VAL1
B -0.319318
C  0.528813
D  0.955057

Element Selection Operations in Pandas DataFrames: Lesson 2

In [524]:
import numpy as np
import pandas as pd

In [525]:
np.random.seed(101)
df = pd.DataFrame(data = np.random.randn(6,5), index = "A B C D E F".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [526]:
df

       VAL1      VAL2      VAL3      VAL4      VAL5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [527]:
df[["VAL2", "VAL5"]]

       VAL2      VAL5
A  0.628133  0.651118
B -0.848077  0.740122
C -0.589001 -0.933237
D  0.190794  0.683509
E  1.693723 -0.134841
F  0.166905  0.072960

In [528]:
variable = ["VAL3", "VAL4"]

In [529]:
df[variable]

       VAL3      VAL4
A  0.907969  0.503826
B  0.605965 -2.018168
C  0.188695 -0.758872
D  1.978757  2.605967
E -1.706086 -1.159119
F  0.184502  0.807706

In [530]:
df

       VAL1      VAL2      VAL3      VAL4      VAL5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [531]:
df["B" : "D"]

       VAL1      VAL2      VAL3      VAL4      VAL5
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509

In [532]:
df[1:4]

       VAL1      VAL2      VAL3      VAL4      VAL5
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509

In [533]:
df["E" : "E"]

       VAL1      VAL2      VAL3      VAL4      VAL5
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841

In [534]:
df[["VAL2" , "VAL5"]] ["E" : "E"]

       VAL2      VAL5
E  1.693723 -0.134841

Top Level Element Selection in Pandas DataFrames: Structure of loc and iloc: Lesson 1

In [535]:
import numpy as np
import pandas as pd

In [536]:
np.random.seed(101)

array = np.random.randint(10, 50, (10, 5))
df = pd.DataFrame(data = array , index = "A B C D E F G H I J".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [537]:
df

   VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [538]:
df.loc["A" : "D"]

   VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29

In [539]:
df.iloc[0:4]

   VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29

In [540]:
df

   VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [541]:
df.loc["C", "VAL4"]

np.int32(39)

In [542]:
df.iloc[2,3]

np.int32(39)

Top Level Element Selection in Pandas DataFrames: Structure of loc and iloc: Lesson 2

In [543]:
import numpy as np
import pandas as pd

In [544]:
np.random.seed(101)

array = np.random.randint(10, 50, (10, 5))
df = pd.DataFrame(data = array , index = "A B C D E F G H I J".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [545]:
df

   VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [546]:
df.loc["C" : "G", "VAL3"]

C    22
D    44
E    41
F    46
G    20
Name: VAL3, dtype: int32

In [547]:
df.loc["C" : "G", ["VAL3"]]

   VAL3
C    22
D    44
E    41
F    46
G    20

In [548]:
df

   VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [549]:
df.iloc[2:7,2]

C    22
D    44
E    41
F    46
G    20
Name: VAL3, dtype: int32

In [550]:
df.iloc[2:7, [2]]

   VAL3
C    22
D    44
E    41
F    46
G    20

In [551]:
df.iloc[2:7] [["VAL3"]]

   VAL3
C    22
D    44
E    41
F    46
G    20

Top Level Element Selection in Pandas DataFrames: Structure of loc and iloc: Lesson 3

In [552]:
import numpy as np
import pandas as pd

In [553]:
np.random.seed(101)
array = np.random.randint(10,50, (10,5))
df = pd.DataFrame(data = array , index = "A B C D E F G H I J".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [554]:
df

   VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [555]:
df.loc["C" : "H", "VAL2" : "VAL4"]

   VAL2  VAL3  VAL4
C    15    22    39
D    39    44    18
E    22    41    33
F    18    46    29
G    17    20    49
H    28    17    49

In [556]:
df.iloc[2:8, 1:4]

   VAL2  VAL3  VAL4
C    15    22    39
D    39    44    18
E    22    41    33
F    18    46    29
G    17    20    49
H    28    17    49

In [557]:
df.iloc[2:8, 1:4].loc["E" : "F", ["VAL3"]]

   VAL3
E    41
F    46

Element Selection with Conditional Operations in Pandas Data Frames

In [558]:
import numpy as np
import pandas as pd

In [559]:
np.random.seed(101)
array = np.random.randint(10,50, (10,5))
df = pd.DataFrame(data = array , index = "A B C D E F G H I J".split(), columns = "VAL1 VAL2 VAL3 VAL4 VAL5".split())

In [560]:
df

   VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [561]:
df > 20

    VAL1   VAL2   VAL3   VAL4   VAL5
A   True   True   True  False   True
B   True  False   True  False   True
C  False  False   True   True   True
D  False   True   True  False   True
E  False   True   True   True  False
F  False  False   True   True   True
G   True  False  False   True   True
H  False   True  False   True   True
I  False   True   True   True   True
J   True   True   True   True   True

In [562]:
df[df>20]

   VAL1  VAL2  VAL3  VAL4  VAL5
A  41.0  21.0  27.0   NaN  33.0
B  21.0   NaN  23.0   NaN  38.0
C   NaN   NaN  22.0  39.0  29.0
D   NaN  39.0  44.0   NaN  29.0
E   NaN  22.0  41.0  33.0   NaN
F   NaN   NaN  46.0  29.0  45.0
G  38.0   NaN   NaN  49.0  48.0
H   NaN  28.0   NaN  49.0  25.0
I   NaN  22.0  27.0  21.0  25.0
J  43.0  39.0  34.0  46.0  29.0

In [563]:
df["VAL1"] < 20

A    False
B    False
C     True
D     True
E    False
F     True
G    False
H     True
I     True
J    False
Name: VAL1, dtype: bool

In [564]:
df[df["VAL1"] < 20]

   VAL1  VAL2  VAL3  VAL4  VAL5
C    10    15    22    39    29
D    18    39    44    18    29
F    19    18    46    29    45
H    19    28    17    49    25
I    10    22    27    21    25

In [565]:
df[df["VAL1"] < 20] ["VAL2"]

C    15
D    39
F    18
H    28
I    22
Name: VAL2, dtype: int32

In [566]:
df[df["VAL1"] < 20][["VAL2"]]

   VAL2
C    15
D    39
F    18
H    28
I    22

In [567]:
df[df["VAL1"] > 20][["VAL2", "VAL5"]]

   VAL2  VAL5
A    21    33
B    19    38
G    17    48
J    39    29

In [568]:
df

   VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [569]:
df[(df["VAL1"] > 20) & (df["VAL4"] < 18)]

   VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38

In [570]:
df[(df < 35) | (df["VAL5"] > 20)]

   VAL1  VAL2  VAL3  VAL4  VAL5
A   NaN  21.0  27.0  16.0  33.0
B  21.0  19.0  23.0  14.0   NaN
C  10.0  15.0  22.0   NaN  29.0
D  18.0   NaN   NaN  18.0  29.0
E  20.0  22.0   NaN  33.0  10.0
F  19.0  18.0   NaN  29.0   NaN
G   NaN  17.0  20.0   NaN   NaN
H  19.0  28.0  17.0   NaN  25.0
I  10.0  22.0  27.0  21.0  25.0
J   NaN   NaN  34.0   NaN  29.0

In [571]:
df

   VAL1  VAL2  VAL3  VAL4  VAL5
A    41    21    27    16    33
B    21    19    23    14    38
C    10    15    22    39    29
D    18    39    44    18    29
E    20    22    41    33    10
F    19    18    46    29    45
G    38    17    20    49    48
H    19    28    17    49    25
I    10    22    27    21    25
J    43    39    34    46    29

In [572]:
df.loc[df.VAL2 > 25, ["VAL2", "VAL3", "VAL5"]]

   VAL2  VAL3  VAL5
D    39    44    29
H    28    17    25
J    39    34    29

Adding Columns to Pandas Data Frames

In [573]:
import numpy as np
import pandas as pd

In [574]:
x = np.arange(0, 28).reshape(7, 4)

In [575]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [576]:
df = pd.DataFrame(data = x, columns = ["VAL1", "VAL2", "VAL3", "VAL4"])

In [577]:
df

   VAL1  VAL2  VAL3  VAL4
0     0     1     2     3
1     4     5     6     7
2     8     9    10    11
3    12    13    14    15
4    16    17    18    19
5    20    21    22    23
6    24    25    26    27

In [578]:
df["VAL1"] + df["VAL2"]

0     1
1     9
2    17
3    25
4    33
5    41
6    49
dtype: int64

In [579]:
df["VAL5"] = df["VAL1"] + df["VAL2"]

In [580]:
df

   VAL1  VAL2  VAL3  VAL4  VAL5
0     0     1     2     3     1
1     4     5     6     7     9
2     8     9    10    11    17
3    12    13    14    15    25
4    16    17    18    19    33
5    20    21    22    23    41
6    24    25    26    27    49

In [581]:
df["VAL6"] = df["VAL3"] * df["VAL4"]

In [582]:
df

   VAL1  VAL2  VAL3  VAL4  VAL5  VAL6
0     0     1     2     3     1     6
1     4     5     6     7     9    42
2     8     9    10    11    17   110
3    12    13    14    15    25   210
4    16    17    18    19    33   342
5    20    21    22    23    41   506
6    24    25    26    27    49   702

In [583]:
np.arange(28, 35)

array([28, 29, 30, 31, 32, 33, 34])

In [584]:
df["VAL7"] = np.arange(28, 35)

In [585]:
df

   VAL1  VAL2  VAL3  VAL4  VAL5  VAL6  VAL7
0     0     1     2     3     1     6    28
1     4     5     6     7     9    42    29
2     8     9    10    11    17   110    30
3    12    13    14    15    25   210    31
4    16    17    18    19    33   342    32
5    20    21    22    23    41   506    33
6    24    25    26    27    49   702    34

In [586]:
df["VAL8"] = [35, 36, 37, 38, 39, 40, 41]

In [587]:
df

   VAL1  VAL2  VAL3  VAL4  VAL5  VAL6  VAL7  VAL8
0     0     1     2     3     1     6    28    35
1     4     5     6     7     9    42    29    36
2     8     9    10    11    17   110    30    37
3    12    13    14    15    25   210    31    38
4    16    17    18    19    33   342    32    39
5    20    21    22    23    41   506    33    40
6    24    25    26    27    49   702    34    41

In [588]:
#df["VAL9"] =[35, 36, 37, 38, 39, 40] (khong du rows)

Removing Rows and Columns from Pandas Data frames

In [589]:
import numpy as np
import pandas as pd

In [590]:
x = np.arange(0, 28).reshape(7, 4)
df = pd.DataFrame(data = x, columns = ["VAL1", "VAL2", "VAL3", "VAL4"])

In [591]:
df

   VAL1  VAL2  VAL3  VAL4
0     0     1     2     3
1     4     5     6     7
2     8     9    10    11
3    12    13    14    15
4    16    17    18    19
5    20    21    22    23
6    24    25    26    27

In [592]:
df.drop(["VAL3", "VAL4"], axis = 1)

   VAL1  VAL2
0     0     1
1     4     5
2     8     9
3    12    13
4    16    17
5    20    21
6    24    25

In [593]:
df

   VAL1  VAL2  VAL3  VAL4
0     0     1     2     3
1     4     5     6     7
2     8     9    10    11
3    12    13    14    15
4    16    17    18    19
5    20    21    22    23
6    24    25    26    27

In [594]:
df.drop(["VAL3", "VAL4"], axis = 1, inplace = True)

In [595]:
df

   VAL1  VAL2
0     0     1
1     4     5
2     8     9
3    12    13
4    16    17
5    20    21
6    24    25

Null Values in Pandas Dataframes

In [596]:
import pandas as pd
import numpy as np

In [597]:
df = pd.DataFrame({'VAL1':[2, 4, np.nan, 6, np.nan, 8, 10],
                   'VAL2':[123, np.nan, 456, np.nan, 789, 246, 357],
                   'VAL3':['France', 'Greece', 'USA', 'Japan', "Sweden", "Norway", "Turkey"]})

In [598]:
df

   VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [599]:
df.isnull()

    VAL1   VAL2   VAL3
0  False  False  False
1  False   True  False
2   True  False  False
3  False   True  False
4   True  False  False
5  False  False  False
6  False  False  False

In [600]:
df.isnull().sum()

VAL1    2
VAL2    2
VAL3    0
dtype: int64

In [601]:
df.isnull().sum() / len(df) * 100

VAL1    28.571429
VAL2    28.571429
VAL3     0.000000
dtype: float64

In [602]:
df.notnull()

    VAL1   VAL2  VAL3
0   True   True  True
1   True  False  True
2  False   True  True
3   True  False  True
4  False   True  True
5   True   True  True
6   True   True  True

In [603]:
df.notnull().sum()

VAL1    5
VAL2    5
VAL3    7
dtype: int64

In [604]:
df.notnull().sum().sum()

np.int64(17)

In [605]:
df["VAL1"].notnull()

0     True
1     True
2    False
3     True
4    False
5     True
6     True
Name: VAL1, dtype: bool

In [606]:
df[df["VAL1"].notnull()]

   VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
3   6.0    NaN   Japan
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [607]:
df

   VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [608]:
df.isnull().any()

VAL1     True
VAL2     True
VAL3    False
dtype: bool

In [609]:
df.isnull().any(axis = 1)

0    False
1     True
2     True
3     True
4     True
5    False
6    False
dtype: bool

In [610]:
condition = df.isnull().any(axis = 1)

In [611]:
df[condition]

   VAL1   VAL2    VAL3
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden

In [612]:
df[~condition]

   VAL1   VAL2    VAL3
0   2.0  123.0  France
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [613]:
df

   VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [614]:
df.notnull().all()

VAL1    False
VAL2    False
VAL3     True
dtype: bool

In [615]:
df.isnull().all(axis = 1)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

Dropping Null Values: Dropna() Function

In [620]:
import pandas as pd
import numpy as np

In [621]:
df = pd.DataFrame({'VAL1':[2, 4, np.nan, 6, np.nan, 8, 10],
                   'VAL2':[123, np.nan, 456, np.nan, 789, 246, 357],
                   'VAL3':['France', 'Greece', 'USA', 'Japan', "Sweden", "Norway", "Turkey"]})

In [622]:
df

   VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [623]:
df.fillna(100000)

       VAL1      VAL2    VAL3
0       2.0     123.0  France
1       4.0  100000.0  Greece
2  100000.0     456.0     USA
3       6.0  100000.0   Japan
4  100000.0     789.0  Sweden
5       8.0     246.0  Norway
6      10.0     357.0  Turkey

In [624]:
df

   VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [625]:
df["VAL1"].fillna(100000)

0         2.0
1         4.0
2    100000.0
3         6.0
4    100000.0
5         8.0
6        10.0
Name: VAL1, dtype: float64

In [626]:
df

   VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [628]:
df['VAL1'].mean()

np.float64(6.0)

In [630]:
df.fillna(df["VAL1"].mean())
df.fillna(df["VAL2"].mean())

    VAL1   VAL2    VAL3
0    2.0  123.0  France
1    4.0  394.2  Greece
2  394.2  456.0     USA
3    6.0  394.2   Japan
4  394.2  789.0  Sweden
5    8.0  246.0  Norway
6   10.0  357.0  Turkey

In [631]:
df.fillna({"VAL1":100000, "VAL2":200000})

       VAL1      VAL2    VAL3
0       2.0     123.0  France
1       4.0  200000.0  Greece
2  100000.0     456.0     USA
3       6.0  200000.0   Japan
4  100000.0     789.0  Sweden
5       8.0     246.0  Norway
6      10.0     357.0  Turkey

In [632]:
df["VAL1"].fillna(df["VAL2"].mean())

0      2.0
1      4.0
2    394.2
3      6.0
4    394.2
5      8.0
6     10.0
Name: VAL1, dtype: float64

In [633]:
df

   VAL1   VAL2    VAL3
0   2.0  123.0  France
1   4.0    NaN  Greece
2   NaN  456.0     USA
3   6.0    NaN   Japan
4   NaN  789.0  Sweden
5   8.0  246.0  Norway
6  10.0  357.0  Turkey

In [634]:
df["VAL3"][0::2]

0    France
2       USA
4    Sweden
6    Turkey
Name: VAL3, dtype: object

In [635]:
df["VAL3"][0::2] = np.nan

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_18584\2477954624.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["VAL3"][0::2] = np.nan
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_18584\2477954624.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["VAL3"][0::2] = np.nan

In [636]:
df

   VAL1   VAL2    VAL3
0   2.0  123.0     NaN
1   4.0    NaN  Greece
2   NaN  456.0     NaN
3   6.0    NaN   Japan
4   NaN  789.0     NaN
5   8.0  246.0  Norway
6  10.0  357.0     NaN

In [637]:
df["VAL3"].fillna("Turkey")

0    Turkey
1    Greece
2    Turkey
3     Japan
4    Turkey
5    Norway
6    Turkey
Name: VAL3, dtype: object

In [638]:
df.fillna(method = "ffill")
df.fillna(method = "pad")
df.fillna(method = "bfill")
df.fillna(method = "backfill")

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_18584\2210248919.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill")
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_18584\2210248919.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "pad")
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_18584\2210248919.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "bfill")
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_18584\2210248919.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "backfill")

   VAL1   VAL2    VAL3
0   2.0  123.0  Greece
1   4.0  456.0  Greece
2   6.0  456.0   Japan
3   6.0  789.0   Japan
4   8.0  789.0  Norway
5   8.0  246.0  Norway
6  10.0  357.0     NaN